### ISSUE TITLE
Alerta cannot load necessary resources

### ISSUE THREAD

**Issue by vykulakov** [alerta/alerta-webui#149]
After updating to the last master Alerta cannot load any necessary resources with 404 error. 

I run Alerta WEB UI under the `/alertabeta` path prefix and it worked fine before updating. But after updating Alerta cannot load any resources.
Also, Alerta does not load `config.json` now and it is quite strange because this file contains some important settings:
```
{
  "endpoint": "https://monitoring.example.com",
  "base_path": "/alertabeta"
}
```
![Screenshot from 2019-04-16 13-06-16](https://user-images.githubusercontent.com/15159594/56201038-b1e50980-6048-11e9-81ba-9449c5a03da7.png)

**Comment by satterly** [comment]
Sorry, but I couldn't get setting the base path (eg. `/alertabeta`) and dynamic routes (eg. `/alert/:id`) to work at the same time with a standard build. If you want to deploy at a subpath you will need to build your own version for now. 

If you can find a way to make it work let me know. I'll document the current limitation when I get a chance.

**Comment by vykulakov** [comment]
Could you provide some instructions to build a version with subpath?

**Comment by satterly** [comment]
Sure.  As soon as I can.

**Comment by satterly** [comment]
Try...
```
$ export VUE_APP_BASE_URL=/alertabeta
$ npm run build
```

**Comment by vykulakov** [comment]
It does not work for me. I've tried `BASE_URL` and `VUE_APP_BASE_URL`, I've tried to put these variables to `.env` and `.env.local` files - there was no result. Only `publicPath` inside `vue.config.js` helped me.

**Comment by satterly** [comment]
So does setting public path and running `npm run build` work then?

**Comment by vykulakov** [comment]
Yes, it works now. But it is not so convenient.

**Comment by satterly** [comment]
I agree it is not great. It is the only way that I know about at present, though. 😞

**Comment by Hipska** [comment]
@satterly Is this currently still the case? What do we have to do today to let Alerta work on a custom path?

**Comment by satterly** [comment]
@Hipska — yes, the situation today is essentially the same. Setting `base_path` in `config.json` alone is not sufficient because the asset URLs in `index.html` and the fetch URL for `config.json` itself are resolved at build time, not at runtime. Only the Vue router base and the OAuth redirect URI honour the runtime value.

The workaround remains: build your own bundle with `BASE_URL` set to the sub-path:

```
$ export BASE_URL=/alerta/
$ npm install
$ npm run build
```

Then serve `dist/` under that same path with an SPA-fallback, eg.

```
location /alerta/ {
  alias /var/www/alerta-webui/dist/;
  try_files \$uri \$uri/ /alerta/index.html;
}
```

I've added a section to the README documenting this so future deployers don't hit the same wall: https://github.com/alerta/alerta-webui/blob/master/README.md#deploying-under-a-sub-path

**Comment by Hipska** [comment]
What a weird way to handle that, I have never seen something like this. Would be cool to have runtime support for that in the future.

**Comment by Hipska** [comment]
@satterly what about just doing `export BASE_URL=''` and then build? Then all links in index.html are relative and should support both root and sub-path..
