### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by sasah** [alerta/alerta-webui#157]
- web UI version: 7.1.0

/**
* Observe a list of Array items.
*/
Observer.prototype.observeArray = function observeArray (items) {
  **for (var i = 0, l = items.length; i < l; i++) {**
    observe(items[i]);
  }
};

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description does not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Gitter chat](https://gitter.im/alerta/chat).

**Comment by sasah** [comment]
[``]([url](url
![out of memory](https://user-images.githubusercontent.com/1188384/56972595-f0fc7a00-6b73-11e9-8028-81c48585681d.png)
))

**Comment by satterly** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.

**Comment by satterly** [comment]
See #155
