### ISSUE TITLE
Refreshing browser breaks alert details page

### ISSUE THREAD

**Issue by satterly** [alerta/alerta-webui#159]
**Issue Summary**
Refreshing browser breaks alert details page

**Environment**
- OS: Linux
- API version: 7.2.0
- Deployment: Docker
- For self-hosted, WSGI environment:  nginx/uwsgi

- Database: MongoDB

- Server config:
  Auth enabled? No
  Auth provider? Google, GitHub, OpenID, Basic, LDAP, etc
  Customer views? No
  (or provide the `/config` endpoint output)

- web UI version: 7.2.0
- CLI version: 6.8.1

**To Reproduce**
1. Go to 'alert details page for an alert'
2. Press cmd-R to refresh page
3. Page breaks
3. See error 

For web app issues, include any web browser JavaScript console errors.

<img width="941" alt="Screenshot 2019-05-03 at 14 33 18" src="https://user-images.githubusercontent.com/615057/57137683-dd8a2280-6db0-11e9-81aa-e365db0a9438.png">

**Expected behavior**
Alert details should just redisplay.

**Screenshots**
above

**Additional context**
none

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by escoand** [comment]
Similar is happening when entering a note and hit the ENTER button.

**Comment by satterly** [comment]
@escoand good to know. Thanks

**Comment by MisterCodo** [comment]
When refreshing browser or pressing enter for a note, getting window in browser stating:

"ERROR: Failed to connect to Alerta API due to missing or invalid config.json file.

Please confirm a config.json file exists, contains an "endpoint" setting and is in the same directory as the application index.html file."

Looking at network, it's trying to get the config.json file using request url http://local.alerta.io:8005/alert/config.json instead of http://local.alerta.io:8005/config.json. 

(I'm running version 7.2.7 keycloack docker example)

**Comment by satterly** [comment]
This is fixed in the docker image by alerta/docker-alerta#470a447a3573f8b505d53a0109fec3cd8c2e4658
