### ISSUE TITLE
Top left hamburger button and Alerta tag behavior change

### ISSUE THREAD

**Issue by MisterCodo** [alerta/alerta-webui#181]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just a suggestion regarding the hamburger button and Alerta tag on top left of page to make it more intuitive.

**Describe the solution you'd like**
When clicking the hamburger button, the animation currently redraws the hamburger button and Alerta tag. Instead I would suggest having both the hamburger button and Alerta tag static, having only the menu below appear, a bit like the desktop youtube webpage does it. Furthermore, having the Alerta tag be a button which brings you back to the main Alerts page would be of help. 

**Describe alternatives you've considered**
Another option would be to move the hamburger button to the top right (next to the refresh button) and upon clicking have a popup menu go down. 

Those are only suggestions, thanks for all your work with Alerta.

**Comment by satterly** [comment]
I'll fix clicking on the logo. That bugs me too.

However you don't actually say why you think changing the way the side nav works is better or what's wrong about the existing behaviour. That would be useful in reviewing your suggestions. Thanks.

**Comment by satterly** [comment]
I've made the toolbar title a clickable link that will take you to Home (ie. the `/alerts` page).

However, I won't be changing the side nav behaviour because I don't see the benefit. Incidentally, I checked the youtube.com website and it works the same way as Alerta web UI currently does...


![Screen Recording 2019-05-21 at 23 53 38 mov](https://user-images.githubusercontent.com/615057/58133742-ed18c080-7c24-11e9-9530-25e58f0bcaf5.gif)

**Comment by MisterCodo** [comment]
I've just read what I wrote and you are correct, I wasn't clear so sorry about that. I have a different behavior for the youtube page, probably given I'm using firefox on windows. The current Alerta behavior is fine though, especially with the toolbar link being clickable, so thanks for making the change and forget anything I said about the side bar animation.
