### ISSUE TITLE
Add Severity in Filters on AlertsList.vue

### ISSUE THREAD

**Issue by orangeman88** [alerta/alerta-webui#198]
On the main alerts page, would it be possible to add a filter for severity? Currently there is status, service, group, client (if applicable) and time.

**Comment by satterly** [comment]
Yes, it's possible. What is your use case? ie. under what circumstances would that be useful?

Did you know you can just type `severity:<SEVERITY_NAME>` (eg. `severity:critical`) into the search box and it will apply the filter to the list?

<img width="1020" alt="Screenshot 2019-06-15 at 12 25 41" src="https://user-images.githubusercontent.com/615057/59550272-ef8ee180-8f68-11e9-8772-950b1e26ad7b.png">

**Comment by orangeman88** [comment]
We have different users that each are more responsible for different types of severities. We did see the option to filter with the text field, however it would be easier to be able to use check boxes on the filter tab.

**Comment by satterly** [comment]
I would not assign responsibility based on alert severity level. I think you're trying to solve the wrong problem by adding `severity` as a filter. Try assigning alerts based on `group` or `service`, which are already both supported as filters in the web UI, instead.

**Comment by jadbaz** [comment]
Is the number of filters intentionally small so that it would all fit in the sidebar?
There are numerous use cases for having more filters.

Why not have something like the current panel feature? It can be hidden so it doesn't obstruct the view and you can fit as many filters as you want there (like all the filters at [explorer.alerta.io](https://explorer.alerta.io)?)
