### ISSUE TITLE
UI lagging

### ISSUE THREAD

**Issue by escoand** [alerta/alerta-webui#213]
**Issue Summary**
I would like to use the new UI but it is lagging more and more with every single event. When I have more than 20 events in the queue and move from one line to an other I have to wait up to one second til the highlighting is visible.
I've profiled the change of the status filter from ACK (3 events) to OPEN+ACK (82 events) in Firefox. This lasts many seconds in which the UI is not responding at all.
[profile.zip](https://github.com/alerta/alerta-webui/files/3380771/profile.zip)

**Environment**
- OS: Linux
- API version: 7.3.0
- Deployment: Docker
- Database: MongoDB
- Server config:
  Auth enabled? Yes
  Auth provider? OpenID
  Customer views? Yes
- web UI version: 7.3.0
- CLI version: 7.3.0

**Expected behavior**
The old UI performed much better without such hangs.

**Comment by satterly** [comment]
Can you provide a typical alert? How many duplicates have the events, on average? And how many history entries?

Can you compare your user experience with the beta website (https://beta.alerta.io), which seems fine to me, and suggest why the performance may be different?

**Comment by escoand** [comment]
> No customer lookup configured for user '...' or '...' (403) 

Can you see the actual mail address in the logs?

**Comment by satterly** [comment]
I've disabled customer lookup. Try again.

**Comment by escoand** [comment]
> Can you compare your user experience with the beta website (https://beta.alerta.io), which seems fine to me, and suggest why the performance may be different?

Yes, same problems there. I've tried the Firefox ESR installed by our department and also Firefox Portable 68. I've still Win7 with IE10 installed which is working in general (login, menu) but not showing any dynamic data. Don't know if Edge would work.

**Comment by satterly** [comment]
How do they compare with Google Chrome?

**Comment by escoand** [comment]
I did more tests at home on Ubuntu with Firefox and Chrome. Same result. Chrome is a bit better but also not perfect. Also tried Chrome on Android with the same problem.

It has to do with the alert list. Every other view and animation is absolutely fast and snappy.

**Comment by satterly** [comment]
I can absolutely believe the alert list is slower than other views because there is so much going onand it actively updates every interval. What we need to understand is if slow performance you have experienced is specific to certain browsers and/or the alerts being displayed.

Do alerts you have generated have a lot of history or a large raw data payload or description text?

Are you applying many filters to the alert summary display or using defaults of open and ack only?

And anything else that might be relevant?

**Comment by escoand** [comment]
![20190711_195358](https://user-images.githubusercontent.com/428567/61073512-e41ec100-a415-11e9-8e5e-fe7a18b0cede.gif)

**Comment by satterly** [comment]
Thanks, that is interesting but doesn't answer any of the questions I asked. If you want me to find the root cause so I can resolve the issue you need to help me reproduce the issue locally. To do that I need to know what makes your environment different to mine and everyone else's. Because as far as I can tell no-one else is experiencing this kind of poor performance.

(Everyone who is should chip in at this point to correct me)

So please answer the above questions as best you can. Thanks again

**Comment by escoand** [comment]
> Do alerts you have generated have a lot of history or a large raw data payload or description text?

As you can see in the GIF it's beta.alerta.io and I did not change anything in the alerts.
 
> Are you applying many filters to the alert summary display or using defaults of open and ack only?

Yes, it is just the default view without any changes to the filters and so on.

> ... I need to know what makes your environment different to mine and everyone else's. Because as far as I can tell no-one else is experiencing this kind of poor performance.

Don't understand why this is only happening to me. I've tested beta.alerta.io with Firefox on Windows and Ubuntu plus Chrome/Chromium on Ubuntu and Android. It's hard to imagine that my 3 absolutely different devices are the only ones having this kind of performance problem.
Tomorrow I'll do more tests with my colleague having Win10.

**Comment by satterly** [comment]
Now that you have pointed it out I can see that it was the beta site, not your own. I'm not sure why you didn't make that point when you uploaded the video -- were you trying to catch me out?

When I asked you those questions it was in good faith. I already said I believed you I just wanted to understand better your environment so I could identify a common root cause if possible.

And now I've just tested the beta site myself and I experience none of the lag you show in your video. So I'm at a loss as to where the performance issue for you might come from. Unless you provide more info, or others experience the same problem, then this issue can't progress any further.

**Comment by satterly** [comment]
Can you try https://beta.alerta.io again? I've made some changes that should hopefully improve general web performance. Thanks.

**Comment by escoand** [comment]
My mobile Chrome is already much much better. I'll do more tests on my work machine with Win7. Thanks so far. Good work.

**Comment by satterly** [comment]
@escoand Have you had a chance to test this at work yet?

**Comment by escoand** [comment]
This is working out quiet well. It's a massive performance boost. Thanks for that.
