### ISSUE TITLE
Alert count are truncated when more than 3 digits 

### ISSUE THREAD

**Issue by sherif84** [alerta/alerta-webui#218]
**Issue Summary**
alerts count is truncated and not visible. since badges are used . 

**Environment**
- OS: Linux
- API version: 7.3.0
- Deployment: Docker

- Database: MongoDB

- web UI version: 7.3.0

**To Reproduce**
1. generate alerts count to be more 1000

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**
count is visible

**Screenshots**
![image](https://user-images.githubusercontent.com/12298259/61832273-9d31c200-ae3e-11e9-8f8c-d396122f6a6c.png)

**Additional context**
I'm not a vue/js experte but from quick reserach swithcing to us v-chip (https://vuetifyjs.com/en/components/chips) could be a  possible solution

**Comment by satterly** [comment]
The fix is to not use badges at all for alert counts because the badge width does not expand to fit the extra digits in Vuetify 1.x. However, this is fixed in Vuetify 2.x so this change will be reverted during the upgrade to Vuetify 2 which should happen in the next 6 months or so.

**Example of badge expanding to contain large count**

<img width="113" alt="Screenshot 2019-07-26 at 00 19 02" src="https://user-images.githubusercontent.com/615057/61912756-4bbb2d00-af3b-11e9-9140-b5a46000361f.png">
