### ISSUE TITLE
note icon remains after deleting note

### ISSUE THREAD

**Issue by 3IMOH** [alerta/alerta-webui#446]
**Issue Summary**
After deleting a note from an alert, the icon (and hover text) remain on the alert summary page.

**To Reproduce**
delete note
view summary page

**Comment by satterly** [comment]
This is because the note is deleted from the notes table but still exists in the alert table in the alert history for that alert (which is an append-only log).

I could include a delete note entry in the alert history. And if that is the most recent "note"-related history entry then don't display a note icon, even if there are older notes.
